SCREEN_WIDTH = 100
SCREEN_HEIGHT = 80

MAP_WIDTH = 100
MAP_HEIGHT = 71

ROOM_MAX_SIZE = 17
ROOM_MIN_SIZE = 9
MAX_ROOMS = 38

BAR_WIDTH = 20
PANEL_HEIGHT = 9
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

FPS = 30

FOV_ALGO = 'BASIC'
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 14
MAX_ROOM_MONSTERS = 5
