import colors

SCREEN_WIDTH = 110
SCREEN_HEIGHT = 60

MAP_WIDTH = 110
MAP_HEIGHT = 51

ROOM_MAX_SIZE = 12
ROOM_MIN_SIZE = 7
MAX_ROOMS = 100

BAR_WIDTH = 20
PANEL_HEIGHT = 9
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

MSG_X = BAR_WIDTH + 30
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 30
MSG_HEIGHT = PANEL_HEIGHT - 1

FPS = 30

FOV_ALGO = 'BASIC'
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 14

MAX_ROOM_MONSTERS = 5
MAX_ROOM_ITEMS = 3

INVENTORY_WIDTH = 50

LIGHTNING_RANGE = 8
LIGHTNING_DAMAGE = 6

CONFUSE_NUM_TURNS = 10
CONFUSE_RANGE = 5

FIREBALL_RADIUS = 5
FIREBALL_DAMAGE = 12

SCROLL_COLOR = colors.lighter_sepia

ITEM_CHANCE = 90
