import colors

SCREEN_WIDTH = 100
SCREEN_HEIGHT = 80

MAP_WIDTH = 100
MAP_HEIGHT = 71

ROOM_MAX_SIZE = 17
ROOM_MIN_SIZE = 9
MAX_ROOMS = 38

BAR_WIDTH = 20
PANEL_HEIGHT = 9
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

FPS = 30

FOV_ALGO = 'BASIC'
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 14

MAX_ROOM_MONSTERS = 5
MAX_ROOM_ITEMS = 2

INVENTORY_WIDTH = 50

LIGHTNING_RANGE = 8
LIGHTNING_DAMAGE = 3

CONFUSE_NUM_TURNS = 10
CONFUSE_RANGE = 5

FIREBALL_RADIUS = 5
FIREBALL_DAMAGE = 12

SCROLL_COLOR = colors.lighter_sepia
